### ISSUE TITLE
Fixing remaining documentation issues with tern.gee

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.gee#24]
# todo

- [x] missing documentation for vars_gee
- [x] undocumented items in gee_methods
- [x] undocumented items in tabulate_gee
- [x] undocumented items in tern_gee_logistic
- [x] undocumented items in lsmeans
- [x] vignettes #12 

```
* checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: ‘emmeans’
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
fit_gee: no visible binding for global variable ‘.id’
fit_gee: no visible binding for global variable ‘.waves’
lsmeans.tern_gee_logistic: no visible global function definition for
  ‘as.formula’
Undefined global functions or variables:
  .id .waves as.formula
Consider adding
  importFrom("stats", "as.formula")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'fit_gee.Rd':
  ‘vars_gee’

See section 'Cross-references' in the 'Writing R Extensions' manual.
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘vars_gee’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'gee_methods'
  ‘x’ ‘sigma’ ‘...’ ‘object’

Undocumented arguments in documentation object 'lsmeans'
  ‘...’

Error: ⚠ R CMD check has warnings
Execution halted
Undocumented arguments in documentation object 'tabulate_gee'
  ‘x’ ‘type’ ‘...’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... WARNING
'library' or 'require' call not declared from: ‘dplyr’
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking LazyData ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking files in ‘vignettes’ ... WARNING
Files in the 'vignettes' directory but no files in 'inst/doc':
  ‘introduction.Rmd’
Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/introduction.Rmd’
(Is a VignetteBuilder field missing?)
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... WARNING
'::' or ':::' import not declared from: ‘dplyr’
* checking tests ... OK
  Running ‘testthat.R’

```

**Comment by edelarua** [comment]
All warning/errors fixed in https://github.com/insightsengineering/tern.gee/pull/4
